# Generated by Django 5.2.1 on 2025-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designations", "0002_alter_designation_deleted_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="designation",
            options={
                "ordering": ["name"],
                "verbose_name": "Designation",
                "verbose_name_plural": "Designations",
            },
        ),
        migrations.AlterField(
            model_name="designation",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
