# Generated by Django 5.2.1 on 2025-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designations", "0003_alter_designation_options_alter_designation_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="designation",
            options={},
        ),
        migrations.AlterField(
            model_name="designation",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
