# Generated by Django 5.2.1 on 2025-06-25 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employees_user"),
        ("salaries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salary",
            options={
                "ordering": ["-payment_date"],
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
            },
        ),
        migrations.AlterField(
            model_name="salary",
            name="allowances",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional allowances provided to the employee.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The base salary for the employee before allowances and deductions.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created."
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_salaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total deductions including unpaid leave, tax, etc.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="Time when record was soft-deleted.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted the record (soft delete).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_salaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="employee",
            field=models.ForeignKey(
                help_text="The employee this salary record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaries",
                to="employees.employees",
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag."),
        ),
        migrations.AlterField(
            model_name="salary",
            name="modified_by",
            field=models.ForeignKey(
                help_text="User who last modified the record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_salaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="net_salary",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Final amount paid to the employee after deductions.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="pay_period_end",
            field=models.DateField(help_text="End date of the salary payment period."),
        ),
        migrations.AlterField(
            model_name="salary",
            name="pay_period_start",
            field=models.DateField(
                help_text="Start date of the salary payment period."
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="payment_date",
            field=models.DateField(
                help_text="Date when the salary was paid or is to be paid."
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of last update."
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salary",
            unique_together={("employee", "pay_period_start", "pay_period_end")},
        ),
    ]
