# Generated by Django 5.2.1 on 2025-06-24 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0002_leavetype_is_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="leave_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_status_changers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
